//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ug_collection_post
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int id_onwser { get; set; }
        public string createAt { get; set; }
    }
}
