//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ug_new_feeds
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string topic { get; set; }
        public string hot { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string images { get; set; }
        public int views { get; set; }
        public string hide { get; set; }
        public string consequence { get; set; }
        public System.DateTime createAt { get; set; }
    }
}
