//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ug_power_point
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string title { get; set; }
        public string tags { get; set; }
        public string images { get; set; }
        public string fileDownload { get; set; }
        public int views { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
    }
}
