//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ug_service
    {
        public int id { get; set; }
        public Nullable<int> id_trade { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> id_onwser { get; set; }
        public Nullable<int> money_agrees { get; set; }
        public string status { get; set; }
        public string images { get; set; }
        public string files { get; set; }
        public string message { get; set; }
        public System.DateTime createAt { get; set; }
        public Nullable<System.DateTime> acceptAt { get; set; }
        public Nullable<System.DateTime> previewAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
    }
}
