//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ug_save_old_avatars
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string avatar { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
    }
}
