//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ug_trade
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> id_onwser { get; set; }
        public Nullable<int> id_service { get; set; }
        public string code_trade { get; set; }
        public Nullable<int> coin { get; set; }
        public string trade_status { get; set; }
        public string status { get; set; }
        public string pay { get; set; }
        public string image_qr { get; set; }
        public string message { get; set; }
        public string name_bank { get; set; }
        public string name_user { get; set; }
        public string number_bank { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
    }
}
