//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class usegoEntities : DbContext
    {
        public usegoEntities()
            : base("name=usegoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ug_archive> ug_archive { get; set; }
        public virtual DbSet<ug_collection_post> ug_collection_post { get; set; }
        public virtual DbSet<ug_comment> ug_comment { get; set; }
        public virtual DbSet<ug_follow> ug_follow { get; set; }
        public virtual DbSet<ug_like_post> ug_like_post { get; set; }
        public virtual DbSet<ug_login_token> ug_login_token { get; set; }
        public virtual DbSet<ug_new_feeds> ug_new_feeds { get; set; }
        public virtual DbSet<ug_power_point> ug_power_point { get; set; }
        public virtual DbSet<ug_respond_comment> ug_respond_comment { get; set; }
        public virtual DbSet<ug_save_old_avatars> ug_save_old_avatars { get; set; }
        public virtual DbSet<ug_service> ug_service { get; set; }
        public virtual DbSet<ug_trade> ug_trade { get; set; }
        public virtual DbSet<ug_users> ug_users { get; set; }
    }
}
